/**
 * Extensions catalogue (anciens + récents) — fusionnées dans VEHICLE_CATALOG.
 * Maintenir / régénérer via scripts/build-vehicle-catalog.mjs + API /api/vehicle-catalog.
 */
import type { FuelType } from '@/types';

type VehiclePreset = {
  brand: string;
  model: string;
  year: number;
  consumption: number;
  fuel: FuelType;
  tank: number;
  odometerUnreliable?: boolean;
  curbWeightKg?: number;
  dragAreaScx?: number;
};

/** Alias de recherche → termes indexés (minuscules). */
export const VEHICLE_SEARCH_ALIASES: Record<string, string[]> = {
  megane: ['mégane', 'megane'],
  'c4 picasso': ['c4 picasso', 'grand c4 picasso', 'c4 spacetourer'],
  '308 sw': ['308 sw', '308 break'],
  golf: ['golf', 'golf viii', 'golf 8', 'golf vii', 'golf 7'],
  'model 3': ['model 3', 'model3', 'tesla 3'],
  'model y': ['model y', 'modely', 'tesla y'],
  twingo: ['twingo', 'twingo 3', 'twingo iii'],
  '206+': ['206+', '206 plus'],
  partner: ['partner', 'partner tepee', 'rifter'],
  citroen: ['citroën', 'citroen'],
  volkswagen: ['volkswagen', 'vw', 'volkswagon'],
  mercedes: ['mercedes', 'mercedes-benz', 'benz'],
  'roland garros': ['roland garros', '806 roland', '806 rg'],
  clio: ['clio', 'clio v', 'clio 5', 'clio iv', 'clio 4'],
  yaris: ['yaris', 'yaris hybrid'],
  duster: ['duster', 'dacia duster'],
  tucson: ['tucson', 'hyundai tucson'],
  qashqai: ['qashqai', 'qashkai'],
  'c-hr': ['c-hr', 'chr', 'c hr'],
  'e-208': ['e-208', 'e208', '208 electrique', '208 électrique'],
};

export const VEHICLE_CATALOG_EXTRA: VehiclePreset[] = [
  // ——— Anciens / classiques FR ———
  { brand: 'Peugeot', model: '205', year: 1995, consumption: 6.8, fuel: 'essence', tank: 50, curbWeightKg: 850 },
  { brand: 'Peugeot', model: '205', year: 1996, consumption: 5.5, fuel: 'diesel', tank: 50, curbWeightKg: 900 },
  { brand: 'Peugeot', model: '306', year: 1998, consumption: 6.2, fuel: 'essence', tank: 60 },
  { brand: 'Peugeot', model: '306', year: 2000, consumption: 5.4, fuel: 'diesel', tank: 60 },
  { brand: 'Peugeot', model: '106', year: 1999, consumption: 6.0, fuel: 'essence', tank: 40 },
  { brand: 'Peugeot', model: '309', year: 1992, consumption: 7.2, fuel: 'essence', tank: 55 },
  { brand: 'Peugeot', model: '405', year: 1995, consumption: 6.8, fuel: 'diesel', tank: 70 },
  { brand: 'Peugeot', model: '605', year: 1996, consumption: 7.5, fuel: 'diesel', tank: 80 },
  { brand: 'Peugeot', model: 'Expert', year: 2005, consumption: 7.2, fuel: 'diesel', tank: 80 },
  { brand: 'Peugeot', model: 'Boxer', year: 2008, consumption: 8.5, fuel: 'diesel', tank: 90 },
  { brand: 'Peugeot', model: '1007', year: 2008, consumption: 5.5, fuel: 'diesel', tank: 40 },
  { brand: 'Peugeot', model: '4007', year: 2009, consumption: 7.2, fuel: 'diesel', tank: 60 },
  { brand: 'Peugeot', model: '4008', year: 2013, consumption: 5.8, fuel: 'diesel', tank: 60 },
  { brand: 'Peugeot', model: '301', year: 2016, consumption: 4.4, fuel: 'diesel', tank: 50 },
  { brand: 'Peugeot', model: '208', year: 2015, consumption: 3.8, fuel: 'diesel', tank: 50, curbWeightKg: 1090 },
  { brand: 'Peugeot', model: '208', year: 2013, consumption: 4.5, fuel: 'essence', tank: 50 },
  { brand: 'Peugeot', model: '2008', year: 2016, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: 'Peugeot', model: '308', year: 2015, consumption: 3.9, fuel: 'diesel', tank: 53 },
  { brand: 'Peugeot', model: '308', year: 2011, consumption: 4.5, fuel: 'diesel', tank: 60 },
  { brand: 'Peugeot', model: '3008', year: 2015, consumption: 4.8, fuel: 'diesel', tank: 60 },
  { brand: 'Peugeot', model: '5008', year: 2015, consumption: 5.2, fuel: 'diesel', tank: 60 },
  { brand: 'Peugeot', model: '508', year: 2015, consumption: 4.2, fuel: 'diesel', tank: 72 },
  { brand: 'Peugeot', model: 'RCZ', year: 2013, consumption: 6.4, fuel: 'essence', tank: 55 },
  { brand: 'Peugeot', model: 'iOn', year: 2012, consumption: 12.5, fuel: 'electrique', tank: 16 },
  { brand: 'Peugeot', model: 'e-2008', year: 2024, consumption: 15.8, fuel: 'electrique', tank: 54 },
  { brand: 'Peugeot', model: 'e-308', year: 2024, consumption: 15.1, fuel: 'electrique', tank: 54 },
  { brand: 'Peugeot', model: '3008', year: 2024, consumption: 5.1, fuel: 'essence', tank: 55 },
  { brand: 'Peugeot', model: '5008', year: 2024, consumption: 5.4, fuel: 'diesel', tank: 56 },
  { brand: 'Peugeot', model: '408', year: 2024, consumption: 5.0, fuel: 'essence', tank: 52 },
  { brand: 'Peugeot', model: '208', year: 2024, consumption: 4.3, fuel: 'essence', tank: 44 },
  { brand: 'Peugeot', model: '208', year: 2025, consumption: 4.2, fuel: 'essence', tank: 44 },
  { brand: 'Peugeot', model: '2008', year: 2025, consumption: 4.9, fuel: 'essence', tank: 44 },

  { brand: 'Citroën', model: 'AX', year: 1995, consumption: 5.8, fuel: 'essence', tank: 40 },
  { brand: 'Citroën', model: 'Saxo', year: 2000, consumption: 6.2, fuel: 'essence', tank: 45 },
  { brand: 'Citroën', model: 'Xsara', year: 2002, consumption: 5.5, fuel: 'diesel', tank: 54 },
  { brand: 'Citroën', model: 'C2', year: 2006, consumption: 4.8, fuel: 'diesel', tank: 41 },
  { brand: 'Citroën', model: 'C3', year: 2008, consumption: 4.5, fuel: 'diesel', tank: 45 },
  { brand: 'Citroën', model: 'C3 Picasso', year: 2012, consumption: 5.0, fuel: 'diesel', tank: 50 },
  { brand: 'Citroën', model: 'C4', year: 2008, consumption: 5.0, fuel: 'diesel', tank: 60 },
  { brand: 'Citroën', model: 'C4 Picasso', year: 2012, consumption: 5.2, fuel: 'diesel', tank: 55 },
  { brand: 'Citroën', model: 'Grand C4 Picasso', year: 2015, consumption: 4.8, fuel: 'diesel', tank: 55 },
  { brand: 'Citroën', model: 'C5', year: 2010, consumption: 5.5, fuel: 'diesel', tank: 71 },
  { brand: 'Citroën', model: 'C6', year: 2008, consumption: 7.0, fuel: 'diesel', tank: 72 },
  { brand: 'Citroën', model: 'Berlingo', year: 2005, consumption: 6.0, fuel: 'diesel', tank: 60 },
  { brand: 'Citroën', model: 'Berlingo', year: 2015, consumption: 4.8, fuel: 'diesel', tank: 53 },
  { brand: 'Citroën', model: 'Nemo', year: 2010, consumption: 4.5, fuel: 'diesel', tank: 45 },
  { brand: 'Citroën', model: 'C-Crosser', year: 2009, consumption: 7.2, fuel: 'diesel', tank: 60 },
  { brand: 'Citroën', model: 'DS3', year: 2013, consumption: 4.4, fuel: 'diesel', tank: 50 },
  { brand: 'Citroën', model: 'DS4', year: 2014, consumption: 4.6, fuel: 'diesel', tank: 60 },
  { brand: 'Citroën', model: 'DS5', year: 2014, consumption: 4.9, fuel: 'diesel', tank: 60 },
  { brand: 'Citroën', model: 'C3', year: 2024, consumption: 4.7, fuel: 'essence', tank: 45 },
  { brand: 'Citroën', model: 'C3 Aircross', year: 2024, consumption: 5.3, fuel: 'essence', tank: 45 },
  { brand: 'Citroën', model: 'C4', year: 2024, consumption: 4.9, fuel: 'essence', tank: 50 },
  { brand: 'Citroën', model: 'ë-C3', year: 2024, consumption: 14.5, fuel: 'electrique', tank: 44 },
  { brand: 'Citroën', model: 'C5 Aircross', year: 2025, consumption: 5.5, fuel: 'diesel', tank: 53 },

  { brand: 'Renault', model: 'R5', year: 1985, consumption: 7.0, fuel: 'essence', tank: 40, odometerUnreliable: true },
  { brand: 'Renault', model: 'Clio I', year: 1995, consumption: 6.5, fuel: 'essence', tank: 43 },
  { brand: 'Renault', model: 'Clio II', year: 2002, consumption: 5.2, fuel: 'diesel', tank: 50 },
  { brand: 'Renault', model: 'Clio III', year: 2008, consumption: 4.5, fuel: 'diesel', tank: 55 },
  { brand: 'Renault', model: 'Clio IV', year: 2014, consumption: 3.6, fuel: 'diesel', tank: 45 },
  { brand: 'Renault', model: 'Twingo I', year: 2000, consumption: 6.0, fuel: 'essence', tank: 40 },
  { brand: 'Renault', model: 'Twingo II', year: 2010, consumption: 4.5, fuel: 'diesel', tank: 40 },
  { brand: 'Renault', model: 'Mégane I', year: 2000, consumption: 5.8, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Mégane II', year: 2006, consumption: 5.2, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Mégane III', year: 2012, consumption: 4.4, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Mégane IV', year: 2018, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: 'Renault', model: 'Scénic I', year: 2000, consumption: 6.5, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Scénic II', year: 2006, consumption: 5.8, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Scénic III', year: 2012, consumption: 5.0, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Scénic IV', year: 2018, consumption: 4.8, fuel: 'diesel', tank: 52 },
  { brand: 'Renault', model: 'Laguna', year: 2005, consumption: 5.8, fuel: 'diesel', tank: 70 },
  { brand: 'Renault', model: 'Laguna III', year: 2010, consumption: 5.2, fuel: 'diesel', tank: 66 },
  { brand: 'Renault', model: 'Espace IV', year: 2008, consumption: 7.0, fuel: 'diesel', tank: 83 },
  { brand: 'Renault', model: 'Espace V', year: 2018, consumption: 5.5, fuel: 'diesel', tank: 58 },
  { brand: 'Renault', model: 'Kangoo', year: 2005, consumption: 6.2, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Kangoo', year: 2015, consumption: 4.8, fuel: 'diesel', tank: 60 },
  { brand: 'Renault', model: 'Trafic', year: 2012, consumption: 7.0, fuel: 'diesel', tank: 80 },
  { brand: 'Renault', model: 'Master', year: 2015, consumption: 8.0, fuel: 'diesel', tank: 105 },
  { brand: 'Renault', model: 'Modus', year: 2008, consumption: 4.8, fuel: 'diesel', tank: 49 },
  { brand: 'Renault', model: 'Captur', year: 2016, consumption: 4.0, fuel: 'diesel', tank: 45 },
  { brand: 'Renault', model: 'Kadjar', year: 2016, consumption: 4.6, fuel: 'diesel', tank: 55 },
  { brand: 'Renault', model: 'Talisman', year: 2018, consumption: 4.5, fuel: 'diesel', tank: 51 },
  { brand: 'Renault', model: 'Zoe', year: 2018, consumption: 13.5, fuel: 'electrique', tank: 41 },
  { brand: 'Renault', model: 'Zoe', year: 2022, consumption: 14.0, fuel: 'electrique', tank: 52 },
  { brand: 'Renault', model: '5 E-Tech', year: 2025, consumption: 14.8, fuel: 'electrique', tank: 52 },
  { brand: 'Renault', model: 'Clio V', year: 2025, consumption: 4.1, fuel: 'essence', tank: 42 },
  { brand: 'Renault', model: 'Captur', year: 2025, consumption: 4.9, fuel: 'essence', tank: 48 },
  { brand: 'Renault', model: 'Austral', year: 2025, consumption: 4.8, fuel: 'essence', tank: 55 },
  { brand: 'Renault', model: 'Rafale', year: 2024, consumption: 5.2, fuel: 'essence', tank: 55 },
  { brand: 'Renault', model: 'Symbioz', year: 2024, consumption: 4.7, fuel: 'essence', tank: 48 },

  { brand: 'Volkswagen', model: 'Golf IV', year: 2002, consumption: 5.5, fuel: 'diesel', tank: 55 },
  { brand: 'Volkswagen', model: 'Golf V', year: 2007, consumption: 5.0, fuel: 'diesel', tank: 55 },
  { brand: 'Volkswagen', model: 'Golf VI', year: 2011, consumption: 4.5, fuel: 'diesel', tank: 55 },
  { brand: 'Volkswagen', model: 'Golf VII', year: 2016, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: 'Volkswagen', model: 'Polo', year: 2005, consumption: 4.8, fuel: 'diesel', tank: 45 },
  { brand: 'Volkswagen', model: 'Polo', year: 2015, consumption: 3.8, fuel: 'diesel', tank: 45 },
  { brand: 'Volkswagen', model: 'Passat', year: 2010, consumption: 5.2, fuel: 'diesel', tank: 70 },
  { brand: 'Volkswagen', model: 'Passat', year: 2018, consumption: 4.6, fuel: 'diesel', tank: 66 },
  { brand: 'Volkswagen', model: 'Touran', year: 2008, consumption: 6.0, fuel: 'diesel', tank: 60 },
  { brand: 'Volkswagen', model: 'Touran', year: 2016, consumption: 4.8, fuel: 'diesel', tank: 58, curbWeightKg: 1550, dragAreaScx: 0.78 },
  { brand: 'Volkswagen', model: 'Tiguan', year: 2014, consumption: 5.5, fuel: 'diesel', tank: 64 },
  { brand: 'Volkswagen', model: 'Tiguan', year: 2020, consumption: 5.2, fuel: 'diesel', tank: 58 },
  { brand: 'Volkswagen', model: 'Caddy', year: 2015, consumption: 5.0, fuel: 'diesel', tank: 60 },
  { brand: 'Volkswagen', model: 'Crafter', year: 2018, consumption: 8.5, fuel: 'diesel', tank: 75 },
  { brand: 'Volkswagen', model: 'ID.3', year: 2024, consumption: 15.5, fuel: 'electrique', tank: 58 },
  { brand: 'Volkswagen', model: 'ID.4', year: 2024, consumption: 17.0, fuel: 'electrique', tank: 77 },
  { brand: 'Volkswagen', model: 'ID.7', year: 2025, consumption: 16.5, fuel: 'electrique', tank: 77 },
  { brand: 'Volkswagen', model: 'Golf VIII', year: 2025, consumption: 4.8, fuel: 'essence', tank: 50 },
  { brand: 'Volkswagen', model: 'T-Roc', year: 2024, consumption: 5.2, fuel: 'essence', tank: 50 },
  { brand: 'Volkswagen', model: 'Tiguan', year: 2025, consumption: 5.4, fuel: 'essence', tank: 55 },

  { brand: 'Toyota', model: 'Yaris', year: 2008, consumption: 4.5, fuel: 'essence', tank: 42 },
  { brand: 'Toyota', model: 'Yaris', year: 2015, consumption: 3.8, fuel: 'essence', tank: 42 },
  { brand: 'Toyota', model: 'Corolla', year: 2010, consumption: 5.0, fuel: 'diesel', tank: 55 },
  { brand: 'Toyota', model: 'Auris', year: 2015, consumption: 4.0, fuel: 'essence', tank: 50 },
  { brand: 'Toyota', model: 'Rav4', year: 2015, consumption: 5.5, fuel: 'diesel', tank: 60 },
  { brand: 'Toyota', model: 'Rav4 Hybrid', year: 2021, consumption: 5.0, fuel: 'essence', tank: 55 },
  { brand: 'Toyota', model: 'Prius', year: 2012, consumption: 4.0, fuel: 'essence', tank: 45 },
  { brand: 'Toyota', model: 'Prius', year: 2020, consumption: 4.2, fuel: 'essence', tank: 43 },
  { brand: 'Toyota', model: 'Aygo', year: 2018, consumption: 4.5, fuel: 'essence', tank: 35 },
  { brand: 'Toyota', model: 'Aygo X', year: 2024, consumption: 4.8, fuel: 'essence', tank: 35 },
  { brand: 'Toyota', model: 'Yaris Cross', year: 2024, consumption: 4.6, fuel: 'essence', tank: 36 },
  { brand: 'Toyota', model: 'Corolla', year: 2024, consumption: 4.5, fuel: 'essence', tank: 43 },
  { brand: 'Toyota', model: 'C-HR', year: 2024, consumption: 4.8, fuel: 'essence', tank: 43 },
  { brand: 'Toyota', model: 'bZ4X', year: 2024, consumption: 16.0, fuel: 'electrique', tank: 71 },

  { brand: 'Ford', model: 'Fiesta', year: 2008, consumption: 4.5, fuel: 'diesel', tank: 45 },
  { brand: 'Ford', model: 'Fiesta', year: 2018, consumption: 4.0, fuel: 'essence', tank: 42 },
  { brand: 'Ford', model: 'Focus', year: 2010, consumption: 4.8, fuel: 'diesel', tank: 55 },
  { brand: 'Ford', model: 'Focus', year: 2019, consumption: 4.5, fuel: 'diesel', tank: 47 },
  { brand: 'Ford', model: 'Mondeo', year: 2012, consumption: 5.2, fuel: 'diesel', tank: 62 },
  { brand: 'Ford', model: 'Kuga', year: 2015, consumption: 5.5, fuel: 'diesel', tank: 60 },
  { brand: 'Ford', model: 'Kuga', year: 2022, consumption: 5.2, fuel: 'essence', tank: 54 },
  { brand: 'Ford', model: 'Puma', year: 2024, consumption: 5.0, fuel: 'essence', tank: 42 },
  { brand: 'Ford', model: 'Transit Custom', year: 2018, consumption: 6.5, fuel: 'diesel', tank: 70 },
  { brand: 'Ford', model: 'Mustang Mach-E', year: 2024, consumption: 17.5, fuel: 'electrique', tank: 91 },

  { brand: 'Opel', model: 'Corsa', year: 2008, consumption: 4.6, fuel: 'diesel', tank: 45 },
  { brand: 'Opel', model: 'Corsa', year: 2018, consumption: 4.2, fuel: 'diesel', tank: 40 },
  { brand: 'Opel', model: 'Astra', year: 2012, consumption: 4.5, fuel: 'diesel', tank: 56 },
  { brand: 'Opel', model: 'Astra', year: 2020, consumption: 4.3, fuel: 'diesel', tank: 48 },
  { brand: 'Opel', model: 'Mokka', year: 2015, consumption: 4.8, fuel: 'diesel', tank: 52 },
  { brand: 'Opel', model: 'Mokka', year: 2023, consumption: 5.0, fuel: 'essence', tank: 44 },
  { brand: 'Opel', model: 'Crossland', year: 2022, consumption: 4.8, fuel: 'essence', tank: 45 },
  { brand: 'Opel', model: 'Grandland', year: 2023, consumption: 5.3, fuel: 'essence', tank: 53 },
  { brand: 'Opel', model: 'Corsa-e', year: 2024, consumption: 15.0, fuel: 'electrique', tank: 50 },

  { brand: 'Dacia', model: 'Logan', year: 2008, consumption: 5.5, fuel: 'diesel', tank: 50 },
  { brand: 'Dacia', model: 'Logan', year: 2018, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: 'Dacia', model: 'Sandero', year: 2015, consumption: 3.9, fuel: 'diesel', tank: 50 },
  { brand: 'Dacia', model: 'Sandero', year: 2024, consumption: 5.0, fuel: 'essence', tank: 50 },
  { brand: 'Dacia', model: 'Duster', year: 2015, consumption: 5.0, fuel: 'diesel', tank: 50 },
  { brand: 'Dacia', model: 'Duster', year: 2025, consumption: 5.2, fuel: 'essence', tank: 50 },
  { brand: 'Dacia', model: 'Jogger', year: 2024, consumption: 5.4, fuel: 'essence', tank: 50 },
  { brand: 'Dacia', model: 'Spring', year: 2024, consumption: 13.0, fuel: 'electrique', tank: 27 },
  { brand: 'Dacia', model: 'Bigster', year: 2025, consumption: 5.5, fuel: 'essence', tank: 50 },

  { brand: 'Hyundai', model: 'i10', year: 2015, consumption: 4.8, fuel: 'essence', tank: 40 },
  { brand: 'Hyundai', model: 'i20', year: 2018, consumption: 4.5, fuel: 'essence', tank: 40 },
  { brand: 'Hyundai', model: 'i30', year: 2016, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: 'Hyundai', model: 'Tucson', year: 2018, consumption: 5.5, fuel: 'diesel', tank: 62 },
  { brand: 'Hyundai', model: 'Tucson', year: 2025, consumption: 5.4, fuel: 'essence', tank: 54 },
  { brand: 'Hyundai', model: 'Kona', year: 2022, consumption: 5.0, fuel: 'essence', tank: 40 },
  { brand: 'Hyundai', model: 'Kona Electric', year: 2024, consumption: 14.5, fuel: 'electrique', tank: 65 },
  { brand: 'Hyundai', model: 'Ioniq 5', year: 2024, consumption: 16.5, fuel: 'electrique', tank: 77 },
  { brand: 'Hyundai', model: 'Ioniq 6', year: 2024, consumption: 14.5, fuel: 'electrique', tank: 77 },

  { brand: 'Kia', model: 'Picanto', year: 2018, consumption: 4.8, fuel: 'essence', tank: 35 },
  { brand: 'Kia', model: 'Rio', year: 2019, consumption: 4.5, fuel: 'essence', tank: 45 },
  { brand: 'Kia', model: 'Ceed', year: 2020, consumption: 4.4, fuel: 'diesel', tank: 50 },
  { brand: 'Kia', model: 'Sportage', year: 2018, consumption: 5.5, fuel: 'diesel', tank: 62 },
  { brand: 'Kia', model: 'Sportage', year: 2024, consumption: 5.3, fuel: 'essence', tank: 54 },
  { brand: 'Kia', model: 'Niro', year: 2023, consumption: 4.8, fuel: 'essence', tank: 42 },
  { brand: 'Kia', model: 'EV6', year: 2024, consumption: 16.0, fuel: 'electrique', tank: 77 },
  { brand: 'Kia', model: 'EV3', year: 2025, consumption: 14.5, fuel: 'electrique', tank: 58 },

  { brand: 'BMW', model: 'Série 1', year: 2015, consumption: 4.5, fuel: 'diesel', tank: 52 },
  { brand: 'BMW', model: 'Série 3', year: 2018, consumption: 4.8, fuel: 'diesel', tank: 57 },
  { brand: 'BMW', model: 'X1', year: 2020, consumption: 5.2, fuel: 'diesel', tank: 51 },
  { brand: 'BMW', model: 'X3', year: 2022, consumption: 5.8, fuel: 'diesel', tank: 65 },
  { brand: 'BMW', model: 'iX1', year: 2024, consumption: 16.5, fuel: 'electrique', tank: 65 },
  { brand: 'BMW', model: 'i4', year: 2024, consumption: 16.0, fuel: 'electrique', tank: 70 },

  { brand: 'Mercedes-Benz', model: 'Classe A', year: 2015, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: 'Mercedes-Benz', model: 'Classe A', year: 2022, consumption: 5.0, fuel: 'essence', tank: 43 },
  { brand: 'Mercedes-Benz', model: 'Classe C', year: 2018, consumption: 4.8, fuel: 'diesel', tank: 66 },
  { brand: 'Mercedes-Benz', model: 'GLA', year: 2021, consumption: 5.2, fuel: 'essence', tank: 43 },
  { brand: 'Mercedes-Benz', model: 'EQA', year: 2024, consumption: 16.5, fuel: 'electrique', tank: 67 },
  { brand: 'Mercedes-Benz', model: 'EQB', year: 2024, consumption: 17.5, fuel: 'electrique', tank: 67 },

  { brand: 'Audi', model: 'A3', year: 2015, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: 'Audi', model: 'A3', year: 2022, consumption: 4.8, fuel: 'essence', tank: 50 },
  { brand: 'Audi', model: 'A4', year: 2018, consumption: 4.6, fuel: 'diesel', tank: 54 },
  { brand: 'Audi', model: 'Q3', year: 2021, consumption: 5.5, fuel: 'essence', tank: 60 },
  { brand: 'Audi', model: 'Q5', year: 2022, consumption: 6.0, fuel: 'diesel', tank: 70 },
  { brand: 'Audi', model: 'Q4 e-tron', year: 2024, consumption: 17.0, fuel: 'electrique', tank: 77 },

  { brand: 'Fiat', model: 'Punto', year: 2010, consumption: 4.5, fuel: 'diesel', tank: 45 },
  { brand: 'Fiat', model: '500', year: 2015, consumption: 4.8, fuel: 'essence', tank: 35 },
  { brand: 'Fiat', model: '500', year: 2022, consumption: 5.0, fuel: 'essence', tank: 35 },
  { brand: 'Fiat', model: '500e', year: 2024, consumption: 13.5, fuel: 'electrique', tank: 42 },
  { brand: 'Fiat', model: 'Panda', year: 2018, consumption: 4.5, fuel: 'essence', tank: 37 },
  { brand: 'Fiat', model: 'Tipo', year: 2020, consumption: 4.4, fuel: 'diesel', tank: 50 },
  { brand: 'Fiat', model: 'Ducato', year: 2018, consumption: 7.5, fuel: 'diesel', tank: 90 },

  { brand: 'Nissan', model: 'Micra', year: 2015, consumption: 4.5, fuel: 'essence', tank: 41 },
  { brand: 'Nissan', model: 'Qashqai', year: 2016, consumption: 4.8, fuel: 'diesel', tank: 55 },
  { brand: 'Nissan', model: 'Qashqai', year: 2023, consumption: 5.2, fuel: 'essence', tank: 55 },
  { brand: 'Nissan', model: 'Juke', year: 2022, consumption: 5.0, fuel: 'essence', tank: 46 },
  { brand: 'Nissan', model: 'Leaf', year: 2020, consumption: 15.0, fuel: 'electrique', tank: 40 },
  { brand: 'Nissan', model: 'Leaf', year: 2024, consumption: 16.0, fuel: 'electrique', tank: 60 },

  { brand: 'Tesla', model: 'Model 3', year: 2025, consumption: 14.0, fuel: 'electrique', tank: 60 },
  { brand: 'Tesla', model: 'Model Y', year: 2024, consumption: 15.5, fuel: 'electrique', tank: 75 },
  { brand: 'Tesla', model: 'Model Y', year: 2025, consumption: 15.0, fuel: 'electrique', tank: 75 },
  { brand: 'Tesla', model: 'Model S', year: 2023, consumption: 16.5, fuel: 'electrique', tank: 100 },

  { brand: 'Skoda', model: 'Fabia', year: 2018, consumption: 4.2, fuel: 'essence', tank: 45 },
  { brand: 'Skoda', model: 'Octavia', year: 2019, consumption: 4.5, fuel: 'diesel', tank: 50 },
  { brand: 'Skoda', model: 'Octavia', year: 2024, consumption: 4.8, fuel: 'essence', tank: 45 },
  { brand: 'Skoda', model: 'Kodiaq', year: 2022, consumption: 5.8, fuel: 'diesel', tank: 60 },
  { brand: 'Skoda', model: 'Enyaq', year: 2024, consumption: 16.5, fuel: 'electrique', tank: 77 },

  { brand: 'Seat', model: 'Ibiza', year: 2018, consumption: 4.5, fuel: 'essence', tank: 40 },
  { brand: 'Seat', model: 'Leon', year: 2020, consumption: 4.4, fuel: 'diesel', tank: 50 },
  { brand: 'Seat', model: 'Arona', year: 2023, consumption: 5.0, fuel: 'essence', tank: 40 },
  { brand: 'Cupra', model: 'Formentor', year: 2024, consumption: 5.5, fuel: 'essence', tank: 50 },
  { brand: 'Cupra', model: 'Born', year: 2024, consumption: 15.5, fuel: 'electrique', tank: 58 },

  { brand: 'Volvo', model: 'V40', year: 2018, consumption: 4.5, fuel: 'diesel', tank: 62 },
  { brand: 'Volvo', model: 'XC40', year: 2022, consumption: 5.5, fuel: 'essence', tank: 54 },
  { brand: 'Volvo', model: 'XC60', year: 2023, consumption: 6.0, fuel: 'essence', tank: 71 },
  { brand: 'Volvo', model: 'EX30', year: 2024, consumption: 15.5, fuel: 'electrique', tank: 51 },
  { brand: 'Volvo', model: 'EX40', year: 2025, consumption: 16.5, fuel: 'electrique', tank: 82 },

  { brand: 'Mini', model: 'Cooper', year: 2018, consumption: 5.0, fuel: 'essence', tank: 44 },
  { brand: 'Mini', model: 'Cooper', year: 2024, consumption: 5.2, fuel: 'essence', tank: 44 },
  { brand: 'Mini', model: 'Countryman', year: 2022, consumption: 5.5, fuel: 'essence', tank: 51 },
  { brand: 'Mini', model: 'Cooper SE', year: 2024, consumption: 14.5, fuel: 'electrique', tank: 33 },

  { brand: 'Suzuki', model: 'Swift', year: 2019, consumption: 4.8, fuel: 'essence', tank: 37 },
  { brand: 'Suzuki', model: 'Vitara', year: 2021, consumption: 5.2, fuel: 'essence', tank: 47 },
  { brand: 'Suzuki', model: 'Ignis', year: 2022, consumption: 4.6, fuel: 'essence', tank: 32 },
  { brand: 'Suzuki', model: 'Swift', year: 2025, consumption: 4.5, fuel: 'essence', tank: 37 },

  { brand: 'Mazda', model: '2', year: 2018, consumption: 4.8, fuel: 'essence', tank: 44 },
  { brand: 'Mazda', model: '3', year: 2021, consumption: 5.2, fuel: 'essence', tank: 51 },
  { brand: 'Mazda', model: 'CX-5', year: 2022, consumption: 5.8, fuel: 'essence', tank: 56 },
  { brand: 'Mazda', model: 'MX-30', year: 2023, consumption: 17.0, fuel: 'electrique', tank: 35 },

  { brand: 'Honda', model: 'Jazz', year: 2018, consumption: 4.8, fuel: 'essence', tank: 40 },
  { brand: 'Honda', model: 'Civic', year: 2020, consumption: 5.0, fuel: 'essence', tank: 47 },
  { brand: 'Honda', model: 'CR-V', year: 2022, consumption: 5.5, fuel: 'essence', tank: 57 },
  { brand: 'Honda', model: 'e:Ny1', year: 2024, consumption: 16.0, fuel: 'electrique', tank: 69 },

  { brand: 'Alfa Romeo', model: 'Giulietta', year: 2015, consumption: 4.5, fuel: 'diesel', tank: 60 },
  { brand: 'Alfa Romeo', model: 'Giulia', year: 2020, consumption: 5.2, fuel: 'diesel', tank: 58 },
  { brand: 'Alfa Romeo', model: 'Stelvio', year: 2022, consumption: 5.8, fuel: 'diesel', tank: 58 },
  { brand: 'Alfa Romeo', model: 'Junior', year: 2025, consumption: 5.0, fuel: 'essence', tank: 44 },

  { brand: 'Jeep', model: 'Renegade', year: 2020, consumption: 5.5, fuel: 'diesel', tank: 48 },
  { brand: 'Jeep', model: 'Compass', year: 2022, consumption: 5.8, fuel: 'diesel', tank: 55 },
  { brand: 'Jeep', model: 'Avenger', year: 2024, consumption: 5.2, fuel: 'essence', tank: 44 },
  { brand: 'Jeep', model: 'Avenger Electric', year: 2024, consumption: 15.5, fuel: 'electrique', tank: 54 },

  { brand: 'DS', model: 'DS 3', year: 2022, consumption: 4.8, fuel: 'essence', tank: 44 },
  { brand: 'DS', model: 'DS 4', year: 2023, consumption: 5.0, fuel: 'essence', tank: 50 },
  { brand: 'DS', model: 'DS 7', year: 2023, consumption: 5.5, fuel: 'essence', tank: 55 },
  { brand: 'DS', model: 'DS 3 E-Tense', year: 2024, consumption: 15.0, fuel: 'electrique', tank: 54 },

  { brand: 'MG', model: 'ZS EV', year: 2024, consumption: 16.5, fuel: 'electrique', tank: 72 },
  { brand: 'MG', model: 'MG4', year: 2024, consumption: 15.5, fuel: 'electrique', tank: 64 },
  { brand: 'MG', model: 'HS', year: 2024, consumption: 6.5, fuel: 'essence', tank: 55 },

  { brand: 'BYD', model: 'Seal U', year: 2025, consumption: 16.5, fuel: 'electrique', tank: 87 },
  { brand: 'BYD', model: 'Atto 2', year: 2025, consumption: 15.0, fuel: 'electrique', tank: 45 },
];
