import type { FuelType } from '@/types';

export type VehiclePreset = {
  brand: string;
  model: string;
  year: number;
  consumption: number;
  fuel: FuelType;
  tank: number;
  /** Si true : défaut hasOdometer=false (sans message UI) */
  odometerUnreliable?: boolean;
};

/** Catalogue searchable (conso & réservoir indicatifs constructeur / moyennes) */
export const VEHICLE_CATALOG: VehiclePreset[] = [
  // Peugeot
  { brand: "Peugeot", model: "108", year: 2018, consumption: 4.6, fuel: 'essence', tank: 35 },
  { brand: "Peugeot", model: "208", year: 2022, consumption: 4.1, fuel: 'essence', tank: 44 },
  { brand: "Peugeot", model: "208", year: 2019, consumption: 3.7, fuel: 'diesel', tank: 50 },
  { brand: "Peugeot", model: "2008", year: 2021, consumption: 4.8, fuel: 'essence', tank: 44 },
  { brand: "Peugeot", model: "308", year: 2022, consumption: 4.2, fuel: 'essence', tank: 52 },
  { brand: "Peugeot", model: "308 SW", year: 2020, consumption: 4.5, fuel: 'diesel', tank: 53 },
  { brand: "Peugeot", model: "3008", year: 2023, consumption: 5, fuel: 'essence', tank: 53 },
  { brand: "Peugeot", model: "3008 Hybrid", year: 2022, consumption: 1.4, fuel: 'essence', tank: 43 },
  { brand: "Peugeot", model: "5008", year: 2022, consumption: 5.3, fuel: 'diesel', tank: 56 },
  { brand: "Peugeot", model: "508", year: 2021, consumption: 4.4, fuel: 'diesel', tank: 55 },
  { brand: "Peugeot", model: "508 SW", year: 2019, consumption: 4.7, fuel: 'diesel', tank: 55 },
  { brand: "Peugeot", model: "Partner", year: 2019, consumption: 5.2, fuel: 'diesel', tank: 60 },
  { brand: "Peugeot", model: "Rifter", year: 2021, consumption: 5, fuel: 'diesel', tank: 51 },
  { brand: "Peugeot", model: "Expert", year: 2020, consumption: 6.4, fuel: 'diesel', tank: 69 },
  { brand: "Peugeot", model: "Boxer", year: 2019, consumption: 7.8, fuel: 'diesel', tank: 90 },
  { brand: "Peugeot", model: "406", year: 2002, consumption: 6.5, fuel: 'diesel', tank: 70 },
  { brand: "Peugeot", model: "407", year: 2007, consumption: 6.8, fuel: 'diesel', tank: 66 },
  { brand: "Peugeot", model: "607", year: 2004, consumption: 7.2, fuel: 'diesel', tank: 80 },
  { brand: "Peugeot", model: "206", year: 2001, consumption: 6.5, fuel: 'essence', tank: 50 },
  { brand: "Peugeot", model: "206+", year: 2011, consumption: 5, fuel: 'diesel', tank: 50 },
  { brand: "Peugeot", model: "207", year: 2010, consumption: 4.6, fuel: 'diesel', tank: 50 },
  { brand: "Peugeot", model: "207 CC", year: 2009, consumption: 6.8, fuel: 'essence', tank: 50 },
  { brand: "Peugeot", model: "1007", year: 2006, consumption: 5.8, fuel: 'essence', tank: 40 },
  { brand: "Peugeot", model: "iOn", year: 2015, consumption: 12.5, fuel: 'electrique', tank: 16 },
  { brand: "Peugeot", model: "e-208", year: 2023, consumption: 15.5, fuel: 'electrique', tank: 50 },
  { brand: "Peugeot", model: "806", year: 1998, consumption: 8.5, fuel: 'diesel', tank: 80, odometerUnreliable: true },
  { brand: "Peugeot", model: "806 Roland Garros", year: 2000, consumption: 8.2, fuel: 'diesel', tank: 80, odometerUnreliable: true },
  { brand: "Peugeot", model: "807", year: 2005, consumption: 7.5, fuel: 'diesel', tank: 80 },
  { brand: "Peugeot", model: "Traveller", year: 2020, consumption: 6.2, fuel: 'diesel', tank: 69 },
  { brand: "Peugeot", model: "Landtrek", year: 2022, consumption: 8, fuel: 'diesel', tank: 80 },
  // Citroën
  { brand: "Citroën", model: "C1", year: 2018, consumption: 4.5, fuel: 'essence', tank: 35 },
  { brand: "Citroën", model: "C3", year: 2022, consumption: 4.6, fuel: 'essence', tank: 45 },
  { brand: "Citroën", model: "C3 Aircross", year: 2021, consumption: 5.2, fuel: 'essence', tank: 45 },
  { brand: "Citroën", model: "C4", year: 2022, consumption: 4.8, fuel: 'essence', tank: 50 },
  { brand: "Citroën", model: "C4 X", year: 2023, consumption: 4.9, fuel: 'essence', tank: 50 },
  { brand: "Citroën", model: "C5 Aircross", year: 2022, consumption: 5.4, fuel: 'diesel', tank: 53 },
  { brand: "Citroën", model: "C5 X", year: 2023, consumption: 5.2, fuel: 'essence', tank: 52 },
  { brand: "Citroën", model: "Berlingo", year: 2022, consumption: 5.1, fuel: 'diesel', tank: 50 },
  { brand: "Citroën", model: "SpaceTourer", year: 2021, consumption: 6.3, fuel: 'diesel', tank: 69 },
  { brand: "Citroën", model: "Jumpy", year: 2020, consumption: 6.5, fuel: 'diesel', tank: 69 },
  { brand: "Citroën", model: "Jumper", year: 2019, consumption: 7.9, fuel: 'diesel', tank: 90 },
  { brand: "Citroën", model: "Ami", year: 2022, consumption: 8, fuel: 'electrique', tank: 5.5 },
  { brand: "Citroën", model: "2CV", year: 1985, consumption: 7.5, fuel: 'essence', tank: 38, odometerUnreliable: true },
  { brand: "Citroën", model: "XSARA Picasso", year: 2005, consumption: 6.5, fuel: 'diesel', tank: 60 },
  { brand: "Citroën", model: "C8", year: 2006, consumption: 7.8, fuel: 'diesel', tank: 80 },
  { brand: "Citroën", model: "C-Elysée", year: 2018, consumption: 4.6, fuel: 'diesel', tank: 50 },
  { brand: "Citroën", model: "ë-C4", year: 2023, consumption: 15, fuel: 'electrique', tank: 50 },
  // Renault
  { brand: "Renault", model: "Twingo", year: 2021, consumption: 5, fuel: 'essence', tank: 35 },
  { brand: "Renault", model: "Clio V", year: 2023, consumption: 4.2, fuel: 'essence', tank: 42 },
  { brand: "Renault", model: "Clio IV", year: 2017, consumption: 3.6, fuel: 'diesel', tank: 45 },
  { brand: "Renault", model: "Captur", year: 2022, consumption: 5, fuel: 'essence', tank: 48 },
  { brand: "Renault", model: "Mégane", year: 2021, consumption: 4.5, fuel: 'diesel', tank: 50 },
  { brand: "Renault", model: "Mégane E-Tech", year: 2023, consumption: 15.5, fuel: 'electrique', tank: 60 },
  { brand: "Renault", model: "Arkana", year: 2023, consumption: 4.8, fuel: 'essence', tank: 50 },
  { brand: "Renault", model: "Austral", year: 2023, consumption: 4.9, fuel: 'essence', tank: 55 },
  { brand: "Renault", model: "Scenic E-Tech", year: 2024, consumption: 16, fuel: 'electrique', tank: 87 },
  { brand: "Renault", model: "Kadjar", year: 2020, consumption: 5.2, fuel: 'diesel', tank: 55 },
  { brand: "Renault", model: "Koleos", year: 2021, consumption: 5.8, fuel: 'diesel', tank: 60 },
  { brand: "Renault", model: "Espace", year: 2020, consumption: 5.5, fuel: 'diesel', tank: 58 },
  { brand: "Renault", model: "Kangoo", year: 2022, consumption: 5.4, fuel: 'diesel', tank: 54 },
  { brand: "Renault", model: "Trafic", year: 2021, consumption: 6.8, fuel: 'diesel', tank: 80 },
  { brand: "Renault", model: "Master", year: 2022, consumption: 8, fuel: 'diesel', tank: 105 },
  { brand: "Renault", model: "Zoe", year: 2022, consumption: 16.5, fuel: 'electrique', tank: 52 },
  { brand: "Renault", model: "Clio II", year: 2003, consumption: 5.8, fuel: 'essence', tank: 50 },
  { brand: "Renault", model: "Clio III", year: 2009, consumption: 4.5, fuel: 'diesel', tank: 45 },
  { brand: "Renault", model: "Scenic", year: 2008, consumption: 6.2, fuel: 'diesel', tank: 60 },
  { brand: "Renault", model: "Laguna", year: 2010, consumption: 5.5, fuel: 'diesel', tank: 66 },
  { brand: "Renault", model: "Talisman", year: 2019, consumption: 4.8, fuel: 'diesel', tank: 51 },
  // Volkswagen
  { brand: "Volkswagen", model: "up!", year: 2019, consumption: 4.4, fuel: 'essence', tank: 35 },
  { brand: "Volkswagen", model: "Polo", year: 2022, consumption: 4.6, fuel: 'essence', tank: 40 },
  { brand: "Volkswagen", model: "Golf VIII", year: 2023, consumption: 4.8, fuel: 'essence', tank: 50 },
  { brand: "Volkswagen", model: "Golf VII", year: 2018, consumption: 4.2, fuel: 'diesel', tank: 50 },
  { brand: "Volkswagen", model: "Golf IV", year: 2002, consumption: 6.5, fuel: 'diesel', tank: 55 },
  { brand: "Volkswagen", model: "ID.3", year: 2023, consumption: 15.5, fuel: 'electrique', tank: 58 },
  { brand: "Volkswagen", model: "ID.4", year: 2023, consumption: 17, fuel: 'electrique', tank: 77 },
  { brand: "Volkswagen", model: "ID.Buzz", year: 2024, consumption: 20, fuel: 'electrique', tank: 77 },
  { brand: "Volkswagen", model: "T-Roc", year: 2022, consumption: 5.2, fuel: 'essence', tank: 50 },
  { brand: "Volkswagen", model: "Tiguan", year: 2023, consumption: 5.6, fuel: 'diesel', tank: 58 },
  { brand: "Volkswagen", model: "Passat", year: 2021, consumption: 4.6, fuel: 'diesel', tank: 66 },
  { brand: "Volkswagen", model: "Arteon", year: 2022, consumption: 5, fuel: 'diesel', tank: 66 },
  { brand: "Volkswagen", model: "Touran", year: 2016, consumption: 5.6, fuel: 'diesel', tank: 58 },
  { brand: "Volkswagen", model: "Touran", year: 2020, consumption: 5.3, fuel: 'diesel', tank: 58 },
  { brand: "Volkswagen", model: "Caddy", year: 2022, consumption: 5.4, fuel: 'diesel', tank: 50 },
  { brand: "Volkswagen", model: "Transporter", year: 2021, consumption: 7.5, fuel: 'diesel', tank: 80 },
  { brand: "Volkswagen", model: "Crafter", year: 2020, consumption: 8.2, fuel: 'diesel', tank: 75 },
  { brand: "Volkswagen", model: "Touareg", year: 2022, consumption: 7.2, fuel: 'diesel', tank: 75 },
  // Toyota
  { brand: "Toyota", model: "Aygo X", year: 2023, consumption: 4.8, fuel: 'essence', tank: 35 },
  { brand: "Toyota", model: "Yaris", year: 2023, consumption: 4.2, fuel: 'essence', tank: 36 },
  { brand: "Toyota", model: "Yaris Hybrid", year: 2023, consumption: 3.8, fuel: 'essence', tank: 36 },
  { brand: "Toyota", model: "Yaris Cross", year: 2023, consumption: 4.5, fuel: 'essence', tank: 42 },
  { brand: "Toyota", model: "Corolla", year: 2023, consumption: 4.4, fuel: 'essence', tank: 43 },
  { brand: "Toyota", model: "Corolla Touring", year: 2022, consumption: 4.5, fuel: 'essence', tank: 43 },
  { brand: "Toyota", model: "C-HR", year: 2023, consumption: 4.7, fuel: 'essence', tank: 43 },
  { brand: "Toyota", model: "RAV4", year: 2023, consumption: 5.4, fuel: 'essence', tank: 55 },
  { brand: "Toyota", model: "RAV4 Hybrid", year: 2023, consumption: 5, fuel: 'essence', tank: 55 },
  { brand: "Toyota", model: "Highlander", year: 2022, consumption: 6.5, fuel: 'essence', tank: 68 },
  { brand: "Toyota", model: "Land Cruiser", year: 2021, consumption: 8.5, fuel: 'diesel', tank: 87 },
  { brand: "Toyota", model: "Hilux", year: 2022, consumption: 7.8, fuel: 'diesel', tank: 80 },
  { brand: "Toyota", model: "Proace", year: 2021, consumption: 6.2, fuel: 'diesel', tank: 69 },
  { brand: "Toyota", model: "Prius", year: 2023, consumption: 4, fuel: 'essence', tank: 43 },
  { brand: "Toyota", model: "bZ4X", year: 2023, consumption: 16.5, fuel: 'electrique', tank: 71 },
  // Mercedes
  { brand: "Mercedes", model: "Classe A", year: 2023, consumption: 5.2, fuel: 'essence', tank: 43 },
  { brand: "Mercedes", model: "Classe B", year: 2021, consumption: 5, fuel: 'diesel', tank: 43 },
  { brand: "Mercedes", model: "CLA", year: 2023, consumption: 5.4, fuel: 'essence', tank: 43 },
  { brand: "Mercedes", model: "Classe C", year: 2023, consumption: 5, fuel: 'diesel', tank: 66 },
  { brand: "Mercedes", model: "Classe E", year: 2022, consumption: 5.5, fuel: 'diesel', tank: 66 },
  { brand: "Mercedes", model: "GLA", year: 2023, consumption: 5.6, fuel: 'essence', tank: 50 },
  { brand: "Mercedes", model: "GLB", year: 2022, consumption: 5.8, fuel: 'diesel', tank: 60 },
  { brand: "Mercedes", model: "GLC", year: 2023, consumption: 6.2, fuel: 'diesel', tank: 65 },
  { brand: "Mercedes", model: "GLE", year: 2022, consumption: 7.5, fuel: 'diesel', tank: 85 },
  { brand: "Mercedes", model: "Vito", year: 2021, consumption: 7.2, fuel: 'diesel', tank: 70 },
  { brand: "Mercedes", model: "Sprinter", year: 2022, consumption: 8.5, fuel: 'diesel', tank: 93 },
  { brand: "Mercedes", model: "EQA", year: 2023, consumption: 16, fuel: 'electrique', tank: 66 },
  { brand: "Mercedes", model: "EQB", year: 2023, consumption: 17, fuel: 'electrique', tank: 66 },
  { brand: "Mercedes", model: "EQC", year: 2022, consumption: 20, fuel: 'electrique', tank: 80 },
  { brand: "Mercedes", model: "W123", year: 1982, consumption: 9.5, fuel: 'diesel', tank: 65, odometerUnreliable: true },
  // BMW
  { brand: "BMW", model: "Série 1", year: 2023, consumption: 5.3, fuel: 'essence', tank: 42 },
  { brand: "BMW", model: "Série 2 Active Tourer", year: 2022, consumption: 5.5, fuel: 'essence', tank: 45 },
  { brand: "BMW", model: "Série 3", year: 2023, consumption: 5, fuel: 'diesel', tank: 59 },
  { brand: "BMW", model: "Série 4", year: 2022, consumption: 5.4, fuel: 'essence', tank: 59 },
  { brand: "BMW", model: "Série 5", year: 2023, consumption: 5.6, fuel: 'diesel', tank: 68 },
  { brand: "BMW", model: "X1", year: 2023, consumption: 5.7, fuel: 'essence', tank: 54 },
  { brand: "BMW", model: "X3", year: 2023, consumption: 6.4, fuel: 'diesel', tank: 65 },
  { brand: "BMW", model: "X5", year: 2022, consumption: 7.8, fuel: 'diesel', tank: 80 },
  { brand: "BMW", model: "iX1", year: 2023, consumption: 16.5, fuel: 'electrique', tank: 64 },
  { brand: "BMW", model: "i4", year: 2023, consumption: 18, fuel: 'electrique', tank: 83 },
  { brand: "BMW", model: "iX", year: 2023, consumption: 21, fuel: 'electrique', tank: 111 },
  { brand: "BMW", model: "E30", year: 1989, consumption: 8.8, fuel: 'essence', tank: 55, odometerUnreliable: true },
  // Audi
  { brand: "Audi", model: "A1", year: 2022, consumption: 5, fuel: 'essence', tank: 40 },
  { brand: "Audi", model: "A3", year: 2023, consumption: 4.8, fuel: 'diesel', tank: 50 },
  { brand: "Audi", model: "A4", year: 2022, consumption: 5, fuel: 'diesel', tank: 54 },
  { brand: "Audi", model: "A5", year: 2021, consumption: 5.3, fuel: 'diesel', tank: 54 },
  { brand: "Audi", model: "A6", year: 2022, consumption: 5.5, fuel: 'diesel', tank: 63 },
  { brand: "Audi", model: "Q2", year: 2022, consumption: 5.4, fuel: 'essence', tank: 45 },
  { brand: "Audi", model: "Q3", year: 2023, consumption: 5.8, fuel: 'diesel', tank: 58 },
  { brand: "Audi", model: "Q5", year: 2022, consumption: 6.2, fuel: 'diesel', tank: 65 },
  { brand: "Audi", model: "Q7", year: 2021, consumption: 7.5, fuel: 'diesel', tank: 85 },
  { brand: "Audi", model: "Q8", year: 2022, consumption: 8, fuel: 'diesel', tank: 85 },
  { brand: "Audi", model: "e-tron", year: 2022, consumption: 22, fuel: 'electrique', tank: 95 },
  { brand: "Audi", model: "Q4 e-tron", year: 2023, consumption: 18, fuel: 'electrique', tank: 82 },
  // Ford
  { brand: "Ford", model: "Fiesta", year: 2021, consumption: 5, fuel: 'essence', tank: 42 },
  { brand: "Ford", model: "Focus", year: 2022, consumption: 5, fuel: 'diesel', tank: 52 },
  { brand: "Ford", model: "Puma", year: 2023, consumption: 5.2, fuel: 'essence', tank: 42 },
  { brand: "Ford", model: "Kuga", year: 2023, consumption: 5.5, fuel: 'essence', tank: 54 },
  { brand: "Ford", model: "Mustang Mach-E", year: 2023, consumption: 18.5, fuel: 'electrique', tank: 91 },
  { brand: "Ford", model: "Explorer", year: 2022, consumption: 7.5, fuel: 'essence', tank: 70 },
  { brand: "Ford", model: "Transit Custom", year: 2022, consumption: 6.8, fuel: 'diesel', tank: 70 },
  { brand: "Ford", model: "Transit", year: 2021, consumption: 8, fuel: 'diesel', tank: 80 },
  { brand: "Ford", model: "Tourneo", year: 2020, consumption: 6.5, fuel: 'diesel', tank: 60 },
  { brand: "Ford", model: "Mondeo", year: 2019, consumption: 4.8, fuel: 'diesel', tank: 62 },
  { brand: "Ford", model: "S-Max", year: 2020, consumption: 5.8, fuel: 'diesel', tank: 63 },
  { brand: "Ford", model: "Ranger", year: 2022, consumption: 7.5, fuel: 'diesel', tank: 80 },
  // Opel
  { brand: "Opel", model: "Corsa", year: 2023, consumption: 4.8, fuel: 'essence', tank: 40 },
  { brand: "Opel", model: "Corsa-e", year: 2023, consumption: 15.5, fuel: 'electrique', tank: 50 },
  { brand: "Opel", model: "Astra", year: 2023, consumption: 5, fuel: 'essence', tank: 52 },
  { brand: "Opel", model: "Mokka", year: 2023, consumption: 5.3, fuel: 'essence', tank: 44 },
  { brand: "Opel", model: "Crossland", year: 2022, consumption: 5, fuel: 'essence', tank: 45 },
  { brand: "Opel", model: "Grandland", year: 2022, consumption: 5.5, fuel: 'diesel', tank: 53 },
  { brand: "Opel", model: "Combo", year: 2021, consumption: 5.2, fuel: 'diesel', tank: 50 },
  { brand: "Opel", model: "Vivaro", year: 2021, consumption: 6.5, fuel: 'diesel', tank: 70 },
  { brand: "Opel", model: "Movano", year: 2020, consumption: 8, fuel: 'diesel', tank: 90 },
  // Dacia
  { brand: "Dacia", model: "Sandero", year: 2023, consumption: 5, fuel: 'essence', tank: 50 },
  { brand: "Dacia", model: "Sandero Stepway", year: 2023, consumption: 5.2, fuel: 'essence', tank: 50 },
  { brand: "Dacia", model: "Logan", year: 2021, consumption: 4.8, fuel: 'diesel', tank: 50 },
  { brand: "Dacia", model: "Duster", year: 2023, consumption: 5.6, fuel: 'diesel', tank: 50 },
  { brand: "Dacia", model: "Jogger", year: 2023, consumption: 5.4, fuel: 'essence', tank: 50 },
  { brand: "Dacia", model: "Spring", year: 2023, consumption: 13.5, fuel: 'electrique', tank: 26 },
  { brand: "Dacia", model: "Lodgy", year: 2019, consumption: 5.2, fuel: 'diesel', tank: 50 },
  { brand: "Dacia", model: "Dokker", year: 2019, consumption: 5.5, fuel: 'diesel', tank: 50 },
  // Fiat
  { brand: "Fiat", model: "Panda", year: 2022, consumption: 5, fuel: 'essence', tank: 35 },
  { brand: "Fiat", model: "500", year: 2022, consumption: 5.2, fuel: 'essence', tank: 35 },
  { brand: "Fiat", model: "500e", year: 2023, consumption: 14, fuel: 'electrique', tank: 42 },
  { brand: "Fiat", model: "Tipo", year: 2021, consumption: 4.8, fuel: 'diesel', tank: 50 },
  { brand: "Fiat", model: "500X", year: 2021, consumption: 5.5, fuel: 'diesel', tank: 48 },
  { brand: "Fiat", model: "Doblo", year: 2020, consumption: 5.8, fuel: 'diesel', tank: 60 },
  { brand: "Fiat", model: "Ducato", year: 2022, consumption: 8.2, fuel: 'diesel', tank: 90 },
  { brand: "Fiat", model: "Scudo", year: 2021, consumption: 6.5, fuel: 'diesel', tank: 69 },
  // Nissan
  { brand: "Nissan", model: "Micra", year: 2021, consumption: 5.2, fuel: 'essence', tank: 41 },
  { brand: "Nissan", model: "Juke", year: 2023, consumption: 5.4, fuel: 'essence', tank: 46 },
  { brand: "Nissan", model: "Qashqai", year: 2023, consumption: 5.2, fuel: 'essence', tank: 55 },
  { brand: "Nissan", model: "X-Trail", year: 2023, consumption: 5.8, fuel: 'essence', tank: 55 },
  { brand: "Nissan", model: "Leaf", year: 2023, consumption: 16.5, fuel: 'electrique', tank: 60 },
  { brand: "Nissan", model: "Ariya", year: 2023, consumption: 18, fuel: 'electrique', tank: 87 },
  { brand: "Nissan", model: "Navara", year: 2021, consumption: 7.5, fuel: 'diesel', tank: 80 },
  { brand: "Nissan", model: "Townstar", year: 2022, consumption: 5.5, fuel: 'diesel', tank: 50 },
  // Hyundai
  { brand: "Hyundai", model: "i10", year: 2023, consumption: 4.8, fuel: 'essence', tank: 36 },
  { brand: "Hyundai", model: "i20", year: 2023, consumption: 5, fuel: 'essence', tank: 40 },
  { brand: "Hyundai", model: "i30", year: 2022, consumption: 5, fuel: 'diesel', tank: 50 },
  { brand: "Hyundai", model: "Kona", year: 2023, consumption: 5.2, fuel: 'essence', tank: 47 },
  { brand: "Hyundai", model: "Kona Electric", year: 2023, consumption: 15, fuel: 'electrique', tank: 64 },
  { brand: "Hyundai", model: "Tucson", year: 2023, consumption: 5.6, fuel: 'diesel', tank: 54 },
  { brand: "Hyundai", model: "Santa Fe", year: 2022, consumption: 6.5, fuel: 'diesel', tank: 67 },
  { brand: "Hyundai", model: "Ioniq 5", year: 2023, consumption: 17.5, fuel: 'electrique', tank: 77 },
  { brand: "Hyundai", model: "Ioniq 6", year: 2023, consumption: 16, fuel: 'electrique', tank: 77 },
  // Kia
  { brand: "Kia", model: "Picanto", year: 2023, consumption: 4.9, fuel: 'essence', tank: 35 },
  { brand: "Kia", model: "Rio", year: 2021, consumption: 5, fuel: 'essence', tank: 45 },
  { brand: "Kia", model: "Ceed", year: 2023, consumption: 5, fuel: 'diesel', tank: 50 },
  { brand: "Kia", model: "Stonic", year: 2022, consumption: 5.3, fuel: 'essence', tank: 45 },
  { brand: "Kia", model: "Niro", year: 2023, consumption: 4.6, fuel: 'essence', tank: 42 },
  { brand: "Kia", model: "Sportage", year: 2023, consumption: 5.5, fuel: 'diesel', tank: 54 },
  { brand: "Kia", model: "Sorento", year: 2022, consumption: 6.4, fuel: 'diesel', tank: 67 },
  { brand: "Kia", model: "EV6", year: 2023, consumption: 17, fuel: 'electrique', tank: 77 },
  { brand: "Kia", model: "EV9", year: 2024, consumption: 20, fuel: 'electrique', tank: 99 },
  // Skoda
  { brand: "Skoda", model: "Fabia", year: 2023, consumption: 4.8, fuel: 'essence', tank: 40 },
  { brand: "Skoda", model: "Scala", year: 2022, consumption: 5, fuel: 'essence', tank: 50 },
  { brand: "Skoda", model: "Octavia", year: 2023, consumption: 4.7, fuel: 'diesel', tank: 45 },
  { brand: "Skoda", model: "Superb", year: 2022, consumption: 5, fuel: 'diesel', tank: 66 },
  { brand: "Skoda", model: "Kamiq", year: 2023, consumption: 5.2, fuel: 'essence', tank: 50 },
  { brand: "Skoda", model: "Karoq", year: 2022, consumption: 5.4, fuel: 'diesel', tank: 55 },
  { brand: "Skoda", model: "Kodiaq", year: 2023, consumption: 6, fuel: 'diesel', tank: 60 },
  { brand: "Skoda", model: "Enyaq", year: 2023, consumption: 16.5, fuel: 'electrique', tank: 77 },
  // Seat
  { brand: "Seat", model: "Ibiza", year: 2023, consumption: 5, fuel: 'essence', tank: 40 },
  { brand: "Seat", model: "Leon", year: 2023, consumption: 4.9, fuel: 'diesel', tank: 45 },
  { brand: "Seat", model: "Arona", year: 2022, consumption: 5.2, fuel: 'essence', tank: 40 },
  { brand: "Seat", model: "Ateca", year: 2022, consumption: 5.5, fuel: 'diesel', tank: 50 },
  { brand: "Seat", model: "Tarraco", year: 2021, consumption: 6, fuel: 'diesel', tank: 58 },
  // Cupra
  { brand: "Cupra", model: "Born", year: 2023, consumption: 15.5, fuel: 'electrique', tank: 58 },
  { brand: "Cupra", model: "Formentor", year: 2023, consumption: 5.4, fuel: 'essence', tank: 50 },
  { brand: "Cupra", model: "Leon", year: 2023, consumption: 5.2, fuel: 'essence', tank: 45 },
  // Volvo
  { brand: "Volvo", model: "XC40", year: 2023, consumption: 5.8, fuel: 'essence', tank: 54 },
  { brand: "Volvo", model: "XC60", year: 2023, consumption: 6.5, fuel: 'diesel', tank: 71 },
  { brand: "Volvo", model: "XC90", year: 2022, consumption: 7.2, fuel: 'diesel', tank: 71 },
  { brand: "Volvo", model: "V60", year: 2022, consumption: 5.5, fuel: 'diesel', tank: 60 },
  { brand: "Volvo", model: "C40", year: 2023, consumption: 17, fuel: 'electrique', tank: 69 },
  { brand: "Volvo", model: "EX30", year: 2024, consumption: 16, fuel: 'electrique', tank: 64 },
  // Mazda
  { brand: "Mazda", model: "Mazda2", year: 2022, consumption: 5, fuel: 'essence', tank: 44 },
  { brand: "Mazda", model: "Mazda3", year: 2023, consumption: 5.2, fuel: 'essence', tank: 51 },
  { brand: "Mazda", model: "CX-30", year: 2023, consumption: 5.5, fuel: 'essence', tank: 48 },
  { brand: "Mazda", model: "CX-5", year: 2022, consumption: 5.8, fuel: 'diesel', tank: 56 },
  { brand: "Mazda", model: "MX-30", year: 2022, consumption: 17, fuel: 'electrique', tank: 35 },
  // Honda
  { brand: "Honda", model: "Jazz", year: 2023, consumption: 4.5, fuel: 'essence', tank: 40 },
  { brand: "Honda", model: "Civic", year: 2023, consumption: 5.2, fuel: 'essence', tank: 46 },
  { brand: "Honda", model: "HR-V", year: 2023, consumption: 5.4, fuel: 'essence', tank: 40 },
  { brand: "Honda", model: "CR-V", year: 2022, consumption: 5.8, fuel: 'essence', tank: 57 },
  { brand: "Honda", model: "e:Ny1", year: 2024, consumption: 16.5, fuel: 'electrique', tank: 68 },
  // Suzuki
  { brand: "Suzuki", model: "Swift", year: 2023, consumption: 4.8, fuel: 'essence', tank: 37 },
  { brand: "Suzuki", model: "Ignis", year: 2022, consumption: 4.6, fuel: 'essence', tank: 32 },
  { brand: "Suzuki", model: "Vitara", year: 2023, consumption: 5.5, fuel: 'essence', tank: 47 },
  { brand: "Suzuki", model: "S-Cross", year: 2022, consumption: 5.4, fuel: 'essence', tank: 47 },
  { brand: "Suzuki", model: "Jimny", year: 2021, consumption: 6.8, fuel: 'essence', tank: 40 },
  // Jeep
  { brand: "Jeep", model: "Avenger", year: 2024, consumption: 5.4, fuel: 'essence', tank: 44 },
  { brand: "Jeep", model: "Renegade", year: 2022, consumption: 5.6, fuel: 'diesel', tank: 48 },
  { brand: "Jeep", model: "Compass", year: 2023, consumption: 5.8, fuel: 'diesel', tank: 55 },
  { brand: "Jeep", model: "Wrangler", year: 2021, consumption: 9.5, fuel: 'essence', tank: 81 },
  // Mini
  { brand: "Mini", model: "Cooper", year: 2023, consumption: 5.4, fuel: 'essence', tank: 44 },
  { brand: "Mini", model: "Countryman", year: 2022, consumption: 5.8, fuel: 'essence', tank: 51 },
  { brand: "Mini", model: "Cooper SE", year: 2023, consumption: 15, fuel: 'electrique', tank: 32 },
  // Tesla
  { brand: "Tesla", model: "Model 3", year: 2024, consumption: 14.5, fuel: 'electrique', tank: 60 },
  { brand: "Tesla", model: "Model Y", year: 2024, consumption: 16, fuel: 'electrique', tank: 75 },
  { brand: "Tesla", model: "Model S", year: 2023, consumption: 18, fuel: 'electrique', tank: 100 },
  { brand: "Tesla", model: "Model X", year: 2023, consumption: 20, fuel: 'electrique', tank: 100 },
  // Porsche
  { brand: "Porsche", model: "Macan", year: 2022, consumption: 9.5, fuel: 'essence', tank: 65 },
  { brand: "Porsche", model: "Cayenne", year: 2022, consumption: 10.5, fuel: 'essence', tank: 75 },
  { brand: "Porsche", model: "Taycan", year: 2023, consumption: 21, fuel: 'electrique', tank: 93 },
  // Alfa
  { brand: "Alfa", model: "Giulia", year: 2022, consumption: 5.8, fuel: 'diesel', tank: 58 },
  { brand: "Alfa", model: "Stelvio", year: 2022, consumption: 6.5, fuel: 'diesel', tank: 58 },
  { brand: "Alfa", model: "Tonale", year: 2023, consumption: 5.6, fuel: 'essence', tank: 50 },
  // LandRover
  { brand: "LandRover", model: "Defender", year: 2023, consumption: 9, fuel: 'diesel', tank: 89 },
  { brand: "LandRover", model: "Discovery", year: 2022, consumption: 8, fuel: 'diesel', tank: 89 },
  { brand: "LandRover", model: "Range Rover Evoque", year: 2023, consumption: 6.5, fuel: 'diesel', tank: 67 },
  { brand: "LandRover", model: "Range Rover Sport", year: 2022, consumption: 8.5, fuel: 'diesel', tank: 90 },
  // Mitsubishi
  { brand: "Mitsubishi", model: "Space Star", year: 2021, consumption: 5, fuel: 'essence', tank: 35 },
  { brand: "Mitsubishi", model: "ASX", year: 2023, consumption: 5.5, fuel: 'essence', tank: 45 },
  { brand: "Mitsubishi", model: "Outlander", year: 2022, consumption: 6, fuel: 'essence', tank: 56 },
  { brand: "Mitsubishi", model: "Eclipse Cross", year: 2022, consumption: 6.2, fuel: 'essence', tank: 45 },
  // MG
  { brand: "MG", model: "MG3", year: 2024, consumption: 5.5, fuel: 'essence', tank: 45 },
  { brand: "MG", model: "ZS", year: 2023, consumption: 5.8, fuel: 'essence', tank: 45 },
  { brand: "MG", model: "HS", year: 2023, consumption: 6.2, fuel: 'essence', tank: 55 },
  { brand: "MG", model: "MG4", year: 2024, consumption: 15.5, fuel: 'electrique', tank: 64 },
  { brand: "MG", model: "MG5", year: 2023, consumption: 16, fuel: 'electrique', tank: 61 },
  // BYD
  { brand: "BYD", model: "Atto 3", year: 2024, consumption: 16, fuel: 'electrique', tank: 60 },
  { brand: "BYD", model: "Dolphin", year: 2024, consumption: 14.5, fuel: 'electrique', tank: 60 },
  { brand: "BYD", model: "Seal", year: 2024, consumption: 16.5, fuel: 'electrique', tank: 82 },
];

/** Favoris affichés en cartes */
export const PRESET_VEHICLES: VehiclePreset[] = [
  VEHICLE_CATALOG.find((v) => v.model === '806 Roland Garros')!,
  VEHICLE_CATALOG.find((v) => v.model === 'Clio V' && v.year === 2023)!,
  VEHICLE_CATALOG.find((v) => v.brand === 'Peugeot' && v.model === '208' && v.year === 2022)!,
  VEHICLE_CATALOG.find((v) => v.model === 'Yaris Hybrid' && v.year === 2023)!,
  VEHICLE_CATALOG.find((v) => v.model === 'Golf VIII')!,
  VEHICLE_CATALOG.find((v) => v.model === 'Model 3')!,
  VEHICLE_CATALOG.find((v) => v.model === 'Duster' && v.year === 2023)!,
  VEHICLE_CATALOG.find((v) => v.model === 'Tucson' && v.year === 2023)!,
].filter(Boolean);

export function searchVehicles(query: string): VehiclePreset[] {
  const q = query.trim().toLowerCase();
  if (!q) return VEHICLE_CATALOG.slice(0, 60);
  return VEHICLE_CATALOG.filter((v) =>
    `${v.brand} ${v.model} ${v.year} ${v.fuel}`.toLowerCase().includes(q)
  ).slice(0, 80);
}

export function listBrands(): string[] {
  return [...new Set(VEHICLE_CATALOG.map((v) => v.brand))].sort((a, b) => a.localeCompare(b, 'fr'));
}
